### ISSUE TITLE
Generate error types

### ISSUE THREAD

**Issue by rawlingsj** [csrwng/origin-schema-generator#1]
This is great BTW and has been extremely useful!

Not being familiar with go I've been trying to work out why I cant get the error types generated.  

https://github.com/GoogleCloudPlatform/kubernetes/tree/master/pkg/api/errors

Is there something in this tool needs to change or should the kubernetes code be in a file called types.go or something?  Probably a dumb question but I've tried to have a go without luck.

In the end I'm hoping to generate something like this where I've generated the schema from a real error JSON response..

``` json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "description": "An error response message",
  "properties": {
    "apiVersion": {
      "type": "string",
      "required": false
    },
    "code": {
      "type": "number",
      "required": false
    },
    "creationTimestamp": {
      "type": "null",
      "required": false
    },
    "details": {
      "type": "object",
      "required": false,
      "properties": {
        "causes": {
          "type": "array",
          "required": false,
          "items": {
            "type": "object",
            "required": false,
            "properties": {
              "field": {
                "type": "string",
                "required": false
              },
              "message": {
                "type": "string",
                "required": false
              },
              "reason": {
                "type": "string",
                "required": false
              }
            }
          }
        },
        "id": {
          "type": "string",
          "required": false
        },
        "kind": {
          "type": "string",
          "required": false
        }
      }
    },
    "kind": {
      "type": "string",
      "required": false
    },
    "message": {
      "type": "string",
      "required": false
    },
    "reason": {
      "type": "string",
      "required": false
    },
    "status": {
      "type": "string",
      "required": false
    }
  }
}
```

**Comment by csrwng** [comment]
The generator will only look at packages that it's told to look at, so to get it to recognize errors, you can add a reference to the errors package here:
https://github.com/csrwng/origin-schema-generator/blob/master/cmd/generate/generate.go#L38
something like:

```
{"github.com/GoogleCloudPlatform/kubernetes/pkg/api/errors", "com.openshift.client.kubernetes.errors", "kubernetes_errors_"}
```

**Comment by rawlingsj** [comment]
Thanks @csrwng, yeah I did try that but they still didn't get generated.  I'll give it another go as I probably did something wrong.

**Comment by csrwng** [comment]
@rawlingsj - sorry I failed to mention that you do need to have a type reference as a member in the Schema struct. 
https://github.com/csrwng/origin-schema-generator/blob/master/cmd/generate/generate.go#L21
That's likely why it failed to generate them before. In the case of the API types, it's enough to point to the higher level types and those pull in all the related structs. For errors, you may need to include each error type as a member of the struct.

**Comment by rawlingsj** [comment]
Hi @csrwng, thanks for coming back to this.

I've tried a couple of things but I still seem to be having an issue.  Can you see anything obvious?

In the import I've included the package..

`kerror "github.com/GoogleCloudPlatform/kubernetes/pkg/api/errors"`

also in the type Schema struct I've added the error type `StatusError` as referenced https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/errors/errors.go#L30 but the error I receive is 

```
cmd/generate/generate.go:27: undefined: "github.com/GoogleCloudPlatform/kubernetes/pkg/api/errors".StatusError
godep: go exit status 2
```

For info, the project has been forked and adapted to use fabric8 package names rather than openshift.  I tried to add a few more steps to the readme but they may not be 100 correct.  If the commits to the docs are useful to you I can put a PR for this repo?
https://github.com/fabric8io/origin-schema-generator/blob/master/README.md

You will probably want to shoot me when you see a horrible hack I added so we can generate a default value to avoid and issue but I couldn't find another way so apologies in advance :) https://github.com/rawlingsj/origin-schema-generator/blob/master/cmd/generate/generate.go#L68

**Comment by rawlingsj** [comment]
Ok so after understanding a bit more about godep I realised I hadn't added the k8s error package as a dependency.  There may be a more correct way but this seems to work for me...

```
go get github.com/GoogleCloudPlatform/kubernetes/pkg/api/errors
godep save ./...
```
